<?php

declare(strict_types=1);

namespace AppBundle\Repository;

/**
 * ActivityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
